# Generated by Django 5.2 on 2025-05-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('order', '0004_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('print_name', models.CharField(blank=True, max_length=255, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('door_no', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_number', models.CharField(blank=True, max_length=100, null=True)),
                ('alternate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('anniversary_date', models.DateField(blank=True, null=True)),
                ('customer_group', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('parent_group', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True)),
                ('opening_balance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('opening_balance_amount_crdr', models.CharField(blank=True, choices=[('CR', 'Credit'), ('DR', 'Debit')], max_length=2, null=True)),
                ('opening_balance_pure_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('opening_balance_pure_weight_crdr', models.CharField(blank=True, choices=[('CR', 'Credit'), ('DR', 'Debit')], max_length=2, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
