# Generated by Django 5.2 on 2025-05-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_account_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='customer_image',
            field=models.ImageField(blank=True, null=True, upload_to='customer_images/'),
        ),
    ]
