# Generated by Django 5.2 on 2025-05-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_account_created_by_account_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
