# Generated by Django 5.2 on 2025-05-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
